export const FECTCH_COLLECTION = {
    FETCH_COLLECTIONS_REQUEST : "FETCH_COLLECTIONS_REQUEST",
    FETCH_COLLECTION_SUCCESS : "FETCH_COLLECTION_SUCCESS",
    FETCH_COLLECTION_FAILURE : "FETCH_COLLECTION_FAILURE"    
} 
